/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import DAO.DAOAutores;
import DAO.DAOCategoria;
import DAO.DAOFuncionario;
import DAO.DAOLivro;
import DAO.DAOUsuario;
import Modelo.Autor;
import Modelo.Categoria;
import Modelo.Funcionario;
import Modelo.Livro;
import Modelo.Usuario;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author joaop
 */
public class TelaAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdm
     */
    public List<Autor> AutoresProv = new ArrayList<>();
    public List<Categoria> CategoriaProv = new ArrayList<>();
    public TelaAdm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAdm = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pCadastroGeral = new javax.swing.JTabbedPane();
        pCadastroFunc = new javax.swing.JPanel();
        tNome = new javax.swing.JLabel();
        tSobrenome = new javax.swing.JLabel();
        tMatricula = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        bCadastra = new javax.swing.JButton();
        cxMatricula = new javax.swing.JTextField();
        cxSobrenome = new javax.swing.JTextField();
        tConfirma = new javax.swing.JLabel();
        pCadastraUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cxUserSobrenome = new javax.swing.JTextField();
        cxUserRegistro = new javax.swing.JTextField();
        cxUserNome = new javax.swing.JTextField();
        bUserCadastra = new javax.swing.JButton();
        tUserConfirma = new javax.swing.JLabel();
        pCategoria = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cxCategoriaTitulo = new javax.swing.JTextField();
        bCategoriaCadastra = new javax.swing.JButton();
        tCategoriaConfirma = new javax.swing.JLabel();
        pCadastraAutor = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cxAutorSobrenome = new javax.swing.JTextField();
        cxAutorNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cxBiografia = new javax.swing.JTextArea();
        bAutorCadastra = new javax.swing.JButton();
        tAutorConfirma = new javax.swing.JLabel();
        pCadastraLivro = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cxLivroNome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lLivrosAutores = new javax.swing.JComboBox<>();
        bLivroAddAutores = new javax.swing.JButton();
        tLivroCategoriaAdd = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lLivrosCategoria = new javax.swing.JComboBox<>();
        bLivroAddCategoria = new javax.swing.JButton();
        tLivroAutoresAdd = new javax.swing.JLabel();
        bLivroCadastrar = new javax.swing.JButton();
        tLivroConfirma = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        lFuncionarioApaga = new javax.swing.JComboBox<>();
        bFuncinonarioApaga = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lAutorApaga = new javax.swing.JComboBox<>();
        bAutorApaga = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        bUsuarioApaga = new javax.swing.JButton();
        lUsuarioApaga = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        bCategoriaApaga = new javax.swing.JButton();
        lCategoriaApaga = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        lLivroApaga = new javax.swing.JComboBox<>();
        bLivroApaga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tNome.setText("Nome");

        tSobrenome.setText("Sobrenome");

        tMatricula.setText("Matrícula");

        bCadastra.setText("Cadastrar");
        bCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastraActionPerformed(evt);
            }
        });

        tConfirma.setText(" ");

        javax.swing.GroupLayout pCadastroFuncLayout = new javax.swing.GroupLayout(pCadastroFunc);
        pCadastroFunc.setLayout(pCadastroFuncLayout);
        pCadastroFuncLayout.setHorizontalGroup(
            pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroFuncLayout.createSequentialGroup()
                .addGroup(pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastroFuncLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tSobrenome)
                            .addComponent(tMatricula)
                            .addComponent(tNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cxNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cxMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                .addComponent(cxSobrenome))))
                    .addGroup(pCadastroFuncLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCadastroFuncLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bCadastra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCadastroFuncLayout.setVerticalGroup(
            pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tSobrenome)
                    .addComponent(cxSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tMatricula)
                    .addComponent(cxMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bCadastra)
                .addGap(69, 69, 69)
                .addComponent(tConfirma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pCadastroGeral.addTab("Funcionário", pCadastroFunc);

        jLabel1.setText("Nome");

        jLabel2.setText("Sobrenome");

        jLabel3.setText("Registro");

        cxUserSobrenome.setText(" ");

        cxUserNome.setText(" ");

        bUserCadastra.setText("Cadastrar");
        bUserCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUserCadastraActionPerformed(evt);
            }
        });

        tUserConfirma.setText(" ");

        javax.swing.GroupLayout pCadastraUserLayout = new javax.swing.GroupLayout(pCadastraUser);
        pCadastraUser.setLayout(pCadastraUserLayout);
        pCadastraUserLayout.setHorizontalGroup(
            pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastraUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bUserCadastra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pCadastraUserLayout.createSequentialGroup()
                        .addGroup(pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cxUserRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(cxUserSobrenome)
                            .addComponent(cxUserNome)))
                    .addComponent(tUserConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCadastraUserLayout.setVerticalGroup(
            pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastraUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cxUserNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cxUserSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cxUserRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bUserCadastra)
                .addGap(58, 58, 58)
                .addComponent(tUserConfirma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pCadastroGeral.addTab("Usuário", pCadastraUser);

        jLabel9.setText("Título");

        bCategoriaCadastra.setText("Cadastrar");
        bCategoriaCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCategoriaCadastraActionPerformed(evt);
            }
        });

        tCategoriaConfirma.setText(" ");

        javax.swing.GroupLayout pCategoriaLayout = new javax.swing.GroupLayout(pCategoria);
        pCategoria.setLayout(pCategoriaLayout);
        pCategoriaLayout.setHorizontalGroup(
            pCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tCategoriaConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pCategoriaLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cxCategoriaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bCategoriaCadastra)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        pCategoriaLayout.setVerticalGroup(
            pCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCategoriaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cxCategoriaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCategoriaCadastra))
                .addGap(12, 12, 12)
                .addComponent(tCategoriaConfirma)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        pCadastroGeral.addTab("Categoria", pCategoria);

        jLabel5.setText("Nome");

        jLabel6.setText("Sobrenome");

        jLabel7.setText("Biografia");

        cxAutorSobrenome.setText(" ");

        cxAutorNome.setText(" ");

        cxBiografia.setColumns(20);
        cxBiografia.setRows(5);
        jScrollPane1.setViewportView(cxBiografia);

        bAutorCadastra.setText("Cadastrar");
        bAutorCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAutorCadastraActionPerformed(evt);
            }
        });

        tAutorConfirma.setText("  ");

        javax.swing.GroupLayout pCadastraAutorLayout = new javax.swing.GroupLayout(pCadastraAutor);
        pCadastraAutor.setLayout(pCadastraAutorLayout);
        pCadastraAutorLayout.setHorizontalGroup(
            pCadastraAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastraAutorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastraAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addGroup(pCadastraAutorLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(41, 41, 41)
                        .addComponent(cxAutorNome))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(bAutorCadastra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tAutorConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pCadastraAutorLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxAutorSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        pCadastraAutorLayout.setVerticalGroup(
            pCadastraAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastraAutorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastraAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cxAutorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastraAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cxAutorSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bAutorCadastra)
                .addGap(31, 31, 31)
                .addComponent(tAutorConfirma)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pCadastroGeral.addTab("Autor", pCadastraAutor);

        jLabel11.setText("Nome do Livro");

        jLabel13.setText("Autor(es)");

        lLivrosAutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Autores" }));
        lLivrosAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lLivrosAutoresActionPerformed(evt);
            }
        });

        bLivroAddAutores.setText("+");
        bLivroAddAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLivroAddAutoresActionPerformed(evt);
            }
        });

        tLivroCategoriaAdd.setText("Categoria(s) adicionadas:");
        tLivroCategoriaAdd.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel15.setText("Categoria(s)");

        lLivrosCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria" }));

        bLivroAddCategoria.setText("+");
        bLivroAddCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLivroAddCategoriaActionPerformed(evt);
            }
        });

        tLivroAutoresAdd.setText("Autor(es) adicionados:");
        tLivroAutoresAdd.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        bLivroCadastrar.setText("Cadastrar");
        bLivroCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLivroCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCadastraLivroLayout = new javax.swing.GroupLayout(pCadastraLivro);
        pCadastraLivro.setLayout(pCadastraLivroLayout);
        pCadastraLivroLayout.setHorizontalGroup(
            pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastraLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tLivroCategoriaAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pCadastraLivroLayout.createSequentialGroup()
                        .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadastraLivroLayout.createSequentialGroup()
                                .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(pCadastraLivroLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(26, 26, 26)))
                        .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cxLivroNome)
                            .addComponent(lLivrosAutores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lLivrosCategoria, 0, 119, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bLivroAddAutores, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(bLivroAddCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(tLivroAutoresAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLivroCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tLivroConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        pCadastraLivroLayout.setVerticalGroup(
            pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastraLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cxLivroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lLivrosAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLivroAddAutores)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lLivrosCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLivroAddCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tLivroAutoresAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tLivroCategoriaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bLivroCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tLivroConfirma)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pCadastroGeral.addTab("Livro", pCadastraLivro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pCadastroGeral)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pCadastroGeral))
        );

        pAdm.addTab("Cadastrar", jPanel1);

        lFuncionarioApaga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionario" }));
        lFuncionarioApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lFuncionarioApagaActionPerformed(evt);
            }
        });

        bFuncinonarioApaga.setText("Confirmar");
        bFuncinonarioApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFuncinonarioApagaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lFuncionarioApaga, 0, 327, Short.MAX_VALUE)
                    .addComponent(bFuncinonarioApaga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lFuncionarioApaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bFuncinonarioApaga)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Funcionário", jPanel3);

        lAutorApaga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Autor" }));
        lAutorApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lAutorApagaActionPerformed(evt);
            }
        });

        bAutorApaga.setText("Confirmar");
        bAutorApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAutorApagaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAutorApaga, 0, 327, Short.MAX_VALUE)
                    .addComponent(bAutorApaga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lAutorApaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAutorApaga)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Autor", jPanel4);

        bUsuarioApaga.setText("Confirmar");
        bUsuarioApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUsuarioApagaActionPerformed(evt);
            }
        });

        lUsuarioApaga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario" }));
        lUsuarioApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lUsuarioApagaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lUsuarioApaga, 0, 327, Short.MAX_VALUE)
                    .addComponent(bUsuarioApaga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lUsuarioApaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bUsuarioApaga)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuario", jPanel6);

        bCategoriaApaga.setText("Confirmar");
        bCategoriaApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCategoriaApagaActionPerformed(evt);
            }
        });

        lCategoriaApaga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria" }));
        lCategoriaApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lCategoriaApagaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCategoriaApaga, 0, 327, Short.MAX_VALUE)
                    .addComponent(bCategoriaApaga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lCategoriaApaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCategoriaApaga)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Categoria", jPanel7);

        lLivroApaga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livro" }));
        lLivroApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lLivroApagaActionPerformed(evt);
            }
        });

        bLivroApaga.setText("Confirmar");
        bLivroApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLivroApagaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lLivroApaga, 0, 327, Short.MAX_VALUE)
                    .addComponent(bLivroApaga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lLivroApaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bLivroApaga)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Livro", jPanel8);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pAdm.addTab("Excluir", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pAdm)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pAdm))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lFuncionarioApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lFuncionarioApagaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_lFuncionarioApagaActionPerformed

    private void bFuncinonarioApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFuncinonarioApagaActionPerformed
        // TODO add your handling code here:
        var oNome = lFuncionarioApaga.getSelectedItem();
        String nome = oNome.toString();
        var cont =  new DAOFuncionario();
        var aux = cont.localizar(nome);
        cont.remover(aux);
        lFuncionarioApaga.setSelectedIndex(0);
        lFuncionarioApaga.removeItem(oNome);
        
        

    }//GEN-LAST:event_bFuncinonarioApagaActionPerformed

    private void lAutorApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lAutorApagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lAutorApagaActionPerformed

    private void bAutorApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAutorApagaActionPerformed
        // TODO add your handling code here:
        var oNome = lAutorApaga.getSelectedItem();
        String nome = oNome.toString();
        var cont =  new DAOAutores();
        var aux = cont.localizar(nome);
        cont.remover(aux);
        lAutorApaga.setSelectedIndex(0);
        lAutorApaga.removeItem(oNome);
        lLivrosAutores.setSelectedIndex(0);
        lLivrosAutores.removeItem(oNome);
    }//GEN-LAST:event_bAutorApagaActionPerformed

    private void bUsuarioApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUsuarioApagaActionPerformed
        // TODO add your handling code here:
        var oNome = lUsuarioApaga.getSelectedItem();
        String nome = oNome.toString();
        var cont =  new DAOUsuario();
        var aux = cont.localizar(nome);
        cont.remover(aux);
        lUsuarioApaga.setSelectedIndex(0);
        lUsuarioApaga.removeItem(oNome);
        
    }//GEN-LAST:event_bUsuarioApagaActionPerformed

    private void lUsuarioApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lUsuarioApagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lUsuarioApagaActionPerformed

    private void bCategoriaApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCategoriaApagaActionPerformed
        // TODO add your handling code here:
        var oNome = lCategoriaApaga.getSelectedItem();
        String nome = oNome.toString();
        var cont =  new DAOCategoria();
        var aux = cont.localizar(nome);
        cont.remover(aux);
        lCategoriaApaga.setSelectedIndex(0);
        lCategoriaApaga.removeItem(oNome);
        lLivrosCategoria.setSelectedIndex(0);
        lLivrosCategoria.removeItem(oNome);
    }//GEN-LAST:event_bCategoriaApagaActionPerformed

    private void lCategoriaApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lCategoriaApagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lCategoriaApagaActionPerformed

    private void lLivroApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lLivroApagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lLivroApagaActionPerformed

    private void bLivroApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLivroApagaActionPerformed
        // TODO add your handling code here:
        var oNome = lLivroApaga.getSelectedItem();
        String nome = oNome.toString();
        var cont =  new DAOLivro();
        var aux = cont.localizar(nome);
        cont.remover(aux);
        lLivroApaga.setSelectedIndex(0);
        lLivroApaga.removeItem(oNome);


        

    }//GEN-LAST:event_bLivroApagaActionPerformed

    private void bLivroCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLivroCadastrarActionPerformed
        // TODO add your handling code here:
        String nome = cxLivroNome.getText();
        var livro = new Livro(nome);
        var cont = new DAOAutores();
        var contCat = new DAOCategoria();
        ArrayList<Autor> listaAutores = cont.getLista();
        ArrayList<Categoria> listaCategoria = contCat.getLista();
        livro.CopiaAutores(listaAutores);
        livro.CopiaCategorias(listaCategoria);
        AutoresProv.clear();
        CategoriaProv.clear();
        tLivroConfirma.setText("Livro adicionado");
        lLivroApaga.addItem(livro.getTitulo());
    }//GEN-LAST:event_bLivroCadastrarActionPerformed

    private void bLivroAddCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLivroAddCategoriaActionPerformed
        // TODO add your handling code here:
        int index  = lLivrosCategoria.getSelectedIndex() - 1;
        var cont = new DAOCategoria();
        var aux =cont.localizar(index);
        CategoriaProv.add(aux);
        String nomes = "";
        for(Categoria categoria : CategoriaProv){
            nomes += categoria.getTitulo() + ", ";
        }
        String total = "Categorias(es) adicionada(s): " + nomes;
        tLivroCategoriaAdd.setText(total);

    }//GEN-LAST:event_bLivroAddCategoriaActionPerformed

    private void bLivroAddAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLivroAddAutoresActionPerformed
        // TODO add your handling code here:
        // Valor subtraido 1 por causa do valor default
        int index  = lLivrosAutores.getSelectedIndex() - 1;
        var cont = new DAOAutores();
        var aux =cont.localizar(index);
        AutoresProv.add(aux);
        String nomes = "";
        for(Autor autor : AutoresProv){
            nomes += autor.getNome() + ", ";
        }
        String total = "Autor(es) adicionado(s): " + nomes;
        tLivroAutoresAdd.setText(total);
    }//GEN-LAST:event_bLivroAddAutoresActionPerformed

    private void lLivrosAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lLivrosAutoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lLivrosAutoresActionPerformed

    private void bAutorCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAutorCadastraActionPerformed
        // TODO add your handling code here:
        String name, sobre,biografia;
        name = cxAutorNome.getText();
        sobre = cxAutorSobrenome.getText();
        biografia = cxBiografia.getText();
        var cont = new DAOAutores();
        var aux = new Autor(name,sobre,biografia);
        cont.incluir(aux);
        tAutorConfirma.setText("Cadastro confirmado");
        lLivrosAutores.addItem(aux.getNome());
        lAutorApaga.addItem(aux.getNome());
    }//GEN-LAST:event_bAutorCadastraActionPerformed

    private void bCategoriaCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCategoriaCadastraActionPerformed
        // TODO add your handling code here:
        String titulo;
        titulo = cxCategoriaTitulo.getText();
        var controller = new DAOCategoria();
        Categoria novo = controller.localizar(titulo);
        if(novo == null){
            Categoria adiciona = new Categoria(titulo);
            controller.incluir(adiciona);
            lLivrosCategoria.addItem(adiciona.getTitulo());
            tCategoriaConfirma.setText("Categoria cadastrada");
            lCategoriaApaga.addItem(adiciona.getTitulo());
            
        }else{
            tCategoriaConfirma.setText("Título já existe, digite outro");
        }
        
        

    }//GEN-LAST:event_bCategoriaCadastraActionPerformed

    private void bUserCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUserCadastraActionPerformed
        // TODO add your handling code here:
        String name, sobre,sRegistro;
        name = cxUserNome.getText();
        sobre = cxUserSobrenome.getText();

        sRegistro = cxUserRegistro.getText();
        try{
            int nReg = Integer.parseInt(sRegistro);
            var cont = new DAOUsuario();
            var aux = new Usuario(name,sobre,nReg);
            if(cont.localizar(nReg) == null){
                cont.incluir(aux);
                tUserConfirma.setText("Cadastro confirmado");
                lUsuarioApaga.addItem(aux.getNome());
            }else{
                tUserConfirma.setText("Numero de registro ja existente");
            }
            
        }catch(NumberFormatException e){
            cxMatricula.setText("Valor invalido");
        }
    }//GEN-LAST:event_bUserCadastraActionPerformed

    private void bCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastraActionPerformed
        // TODO add your handling code here:
        String name, sobre,sMatricula;

        name = cxNome.getText();
        sobre = cxSobrenome.getText();
        sMatricula = cxMatricula.getText();
        try{
            int nMat = Integer.parseInt(sMatricula);
            DAOFuncionario cont = new DAOFuncionario();
            Funcionario aux = new Funcionario(name,sobre,nMat);
            if(cont.localizar(aux) ==  null){
                cont.incluir(aux);
                lFuncionarioApaga.addItem(aux.getNome());
                tConfirma.setText("Cadastro confirmado");
            }else{
                tConfirma.setText("Matricula ja existente");
            }
        }catch(NumberFormatException e){
            cxMatricula.setText("Valor invalido");
        }
    }//GEN-LAST:event_bCadastraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAutorApaga;
    private javax.swing.JButton bAutorCadastra;
    private javax.swing.JButton bCadastra;
    private javax.swing.JButton bCategoriaApaga;
    private javax.swing.JButton bCategoriaCadastra;
    private javax.swing.JButton bFuncinonarioApaga;
    private javax.swing.JButton bLivroAddAutores;
    private javax.swing.JButton bLivroAddCategoria;
    private javax.swing.JButton bLivroApaga;
    private javax.swing.JButton bLivroCadastrar;
    private javax.swing.JButton bUserCadastra;
    private javax.swing.JButton bUsuarioApaga;
    private javax.swing.JTextField cxAutorNome;
    private javax.swing.JTextField cxAutorSobrenome;
    private javax.swing.JTextArea cxBiografia;
    private javax.swing.JTextField cxCategoriaTitulo;
    private javax.swing.JTextField cxLivroNome;
    private javax.swing.JTextField cxMatricula;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxSobrenome;
    private javax.swing.JTextField cxUserNome;
    private javax.swing.JTextField cxUserRegistro;
    private javax.swing.JTextField cxUserSobrenome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> lAutorApaga;
    private javax.swing.JComboBox<String> lCategoriaApaga;
    private javax.swing.JComboBox<String> lFuncionarioApaga;
    private javax.swing.JComboBox<String> lLivroApaga;
    private javax.swing.JComboBox<String> lLivrosAutores;
    private javax.swing.JComboBox<String> lLivrosCategoria;
    private javax.swing.JComboBox<String> lUsuarioApaga;
    private javax.swing.JTabbedPane pAdm;
    private javax.swing.JPanel pCadastraAutor;
    private javax.swing.JPanel pCadastraLivro;
    private javax.swing.JPanel pCadastraUser;
    private javax.swing.JPanel pCadastroFunc;
    private javax.swing.JTabbedPane pCadastroGeral;
    private javax.swing.JPanel pCategoria;
    private javax.swing.JLabel tAutorConfirma;
    private javax.swing.JLabel tCategoriaConfirma;
    private javax.swing.JLabel tConfirma;
    private javax.swing.JLabel tLivroAutoresAdd;
    private javax.swing.JLabel tLivroCategoriaAdd;
    private javax.swing.JLabel tLivroConfirma;
    private javax.swing.JLabel tMatricula;
    private javax.swing.JLabel tNome;
    private javax.swing.JLabel tSobrenome;
    private javax.swing.JLabel tUserConfirma;
    // End of variables declaration//GEN-END:variables
}
