/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import DAO.DAOAutores;
import DAO.DAOCategoria;
import DAO.DAOFuncionario;
import DAO.DAOUsuario;
import Modelo.Autor;
import Modelo.Categoria;
import Modelo.Funcionario;
import Modelo.Usuario;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author joaop
 */
public class TelaAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdm
     */
    public List<Autor> AutoresProv = new ArrayList<>();
    public List<Categoria> CategoriaProv = new ArrayList<>();
    public TelaAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAdm = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pCadastroGeral = new javax.swing.JTabbedPane();
        pCadastroFunc = new javax.swing.JPanel();
        tNome = new javax.swing.JLabel();
        tSobrenome = new javax.swing.JLabel();
        tMatricula = new javax.swing.JLabel();
        tId = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        bCadastra = new javax.swing.JButton();
        cxMatricula = new javax.swing.JTextField();
        cxSobrenome = new javax.swing.JTextField();
        cxId = new javax.swing.JTextField();
        tConfirma = new javax.swing.JLabel();
        pCadastraUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cxUserSobrenome = new javax.swing.JTextField();
        cxUserRegistro = new javax.swing.JTextField();
        cxUserId = new javax.swing.JTextField();
        cxUserNome = new javax.swing.JTextField();
        bUserCadastra = new javax.swing.JButton();
        tUserConfirma = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cxAutorSobrenome = new javax.swing.JTextField();
        cxAutorNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cxBiografia = new javax.swing.JTextArea();
        bAutorCadastra = new javax.swing.JButton();
        tAutorConfirma = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cxAutorId = new javax.swing.JTextField();
        pCategoria = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cxCategoriaTitulo = new javax.swing.JTextField();
        cxCategoriaId = new javax.swing.JTextField();
        bCategoriaCadastra = new javax.swing.JButton();
        tCategoriaConfirma = new javax.swing.JLabel();
        pCadastraLivro = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cxLivroNome = new javax.swing.JTextField();
        cxLivroId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lLivrosAutores = new javax.swing.JComboBox<>();
        bLivroAddAutores = new javax.swing.JButton();
        tLivroCategoriaAdd = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lLivrosCategoria = new javax.swing.JComboBox<>();
        bLivroAddCategoria = new javax.swing.JButton();
        tLivroAutoresAdd = new javax.swing.JLabel();
        bLivroCadastrar = new javax.swing.JButton();
        tLivroConfirma = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tNome.setText("Nome");

        tSobrenome.setText("Sobrenome");

        tMatricula.setText("Matrícula");

        tId.setText("ID");

        bCadastra.setText("Cadastrar");
        bCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastraActionPerformed(evt);
            }
        });

        tConfirma.setText(" ");

        javax.swing.GroupLayout pCadastroFuncLayout = new javax.swing.GroupLayout(pCadastroFunc);
        pCadastroFunc.setLayout(pCadastroFuncLayout);
        pCadastroFuncLayout.setHorizontalGroup(
            pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroFuncLayout.createSequentialGroup()
                .addGroup(pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastroFuncLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tSobrenome)
                            .addComponent(tMatricula)
                            .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cxNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cxId, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                .addComponent(cxMatricula)
                                .addComponent(cxSobrenome))))
                    .addGroup(pCadastroFuncLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bCadastra, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(tConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCadastroFuncLayout.setVerticalGroup(
            pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tSobrenome)
                    .addComponent(cxSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tMatricula)
                    .addComponent(cxMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tId)
                    .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(bCadastra)
                .addGap(18, 18, 18)
                .addComponent(tConfirma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pCadastroGeral.addTab("Funcionário", pCadastroFunc);

        jLabel1.setText("Nome");

        jLabel2.setText("Sobrenome");

        jLabel3.setText("Registro");

        jLabel4.setText("ID");

        cxUserSobrenome.setText(" ");

        cxUserNome.setText(" ");

        bUserCadastra.setText("Cadastrar");
        bUserCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUserCadastraActionPerformed(evt);
            }
        });

        tUserConfirma.setText(" ");

        javax.swing.GroupLayout pCadastraUserLayout = new javax.swing.GroupLayout(pCadastraUser);
        pCadastraUser.setLayout(pCadastraUserLayout);
        pCadastraUserLayout.setHorizontalGroup(
            pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastraUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bUserCadastra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pCadastraUserLayout.createSequentialGroup()
                        .addGroup(pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cxUserId, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(cxUserRegistro)
                            .addComponent(cxUserSobrenome)
                            .addComponent(cxUserNome)))
                    .addComponent(tUserConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCadastraUserLayout.setVerticalGroup(
            pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastraUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cxUserNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cxUserSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cxUserRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastraUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cxUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bUserCadastra)
                .addGap(18, 18, 18)
                .addComponent(tUserConfirma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pCadastroGeral.addTab("Usuário", pCadastraUser);

        jLabel5.setText("Nome");

        jLabel6.setText("Sobrenome");

        jLabel7.setText("Biografia");

        cxAutorSobrenome.setText(" ");

        cxAutorNome.setText(" ");

        cxBiografia.setColumns(20);
        cxBiografia.setRows(5);
        jScrollPane1.setViewportView(cxBiografia);

        bAutorCadastra.setText("Cadastrar");
        bAutorCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAutorCadastraActionPerformed(evt);
            }
        });

        tAutorConfirma.setText("  ");

        jLabel8.setText("ID");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(41, 41, 41)
                        .addComponent(cxAutorNome))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(bAutorCadastra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tAutorConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxAutorId, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxAutorSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cxAutorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cxAutorSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cxAutorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bAutorCadastra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tAutorConfirma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pCadastroGeral.addTab("Autor", jPanel5);

        jLabel9.setText("Título");

        jLabel10.setText("ID");

        bCategoriaCadastra.setText("Cadastrar");
        bCategoriaCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCategoriaCadastraActionPerformed(evt);
            }
        });

        tCategoriaConfirma.setText(" ");

        javax.swing.GroupLayout pCategoriaLayout = new javax.swing.GroupLayout(pCategoria);
        pCategoria.setLayout(pCategoriaLayout);
        pCategoriaLayout.setHorizontalGroup(
            pCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(bCategoriaCadastra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tCategoriaConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cxCategoriaId, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(cxCategoriaTitulo)))
        );
        pCategoriaLayout.setVerticalGroup(
            pCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCategoriaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cxCategoriaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cxCategoriaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCategoriaCadastra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tCategoriaConfirma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pCadastroGeral.addTab("Categoria", pCategoria);

        jLabel11.setText("Nome do Livro");

        jLabel12.setText("Id");

        jLabel13.setText("Autor(es)");

        lLivrosAutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Autores" }));
        lLivrosAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lLivrosAutoresActionPerformed(evt);
            }
        });

        bLivroAddAutores.setText("+");
        bLivroAddAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLivroAddAutoresActionPerformed(evt);
            }
        });

        tLivroCategoriaAdd.setText("Categoria(s) adicionadas:");
        tLivroCategoriaAdd.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel15.setText("Categoria(s)");

        lLivrosCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria" }));

        bLivroAddCategoria.setText("+");
        bLivroAddCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLivroAddCategoriaActionPerformed(evt);
            }
        });

        tLivroAutoresAdd.setText("Autor(es) adicionados:");
        tLivroAutoresAdd.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        bLivroCadastrar.setText("Cadastrar");

        javax.swing.GroupLayout pCadastraLivroLayout = new javax.swing.GroupLayout(pCadastraLivro);
        pCadastraLivro.setLayout(pCadastraLivroLayout);
        pCadastraLivroLayout.setHorizontalGroup(
            pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastraLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tLivroCategoriaAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pCadastraLivroLayout.createSequentialGroup()
                        .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadastraLivroLayout.createSequentialGroup()
                                .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(pCadastraLivroLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(26, 26, 26)))
                        .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cxLivroId, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(cxLivroNome)
                            .addComponent(lLivrosAutores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lLivrosCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bLivroAddAutores, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(bLivroAddCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(tLivroAutoresAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLivroCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tLivroConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        pCadastraLivroLayout.setVerticalGroup(
            pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastraLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cxLivroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxLivroId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lLivrosAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLivroAddAutores)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastraLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lLivrosCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLivroAddCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tLivroAutoresAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tLivroCategoriaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bLivroCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tLivroConfirma)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pCadastroGeral.addTab("Livro", pCadastraLivro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(pCadastroGeral)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pCadastroGeral))
        );

        pAdm.addTab("Cadastrar", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        pAdm.addTab("Excluir", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pAdm)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pAdm))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastraActionPerformed
        // TODO add your handling code here:
        String name, sobre,sId,sMatricula;
        
        name = cxNome.getText();
        sobre = cxSobrenome.getText();
        sId = cxId.getText();
        sMatricula = cxMatricula.getText();
        try{
            int nId = Integer.parseInt(sId);
            try{
                int nMat = Integer.parseInt(sMatricula);
                DAOFuncionario cont = new DAOFuncionario();
                Funcionario aux = new Funcionario(nId,name,sobre,nMat);
                cont.incluir(aux);
                tConfirma.setText("Cadastro confirmado");
            }catch(NumberFormatException e){        
                cxMatricula.setText("Valor invalido");      
            }  
        }catch(NumberFormatException e){        
            cxId.setText("Valor invalido"); 
        }
        

    }//GEN-LAST:event_bCadastraActionPerformed

    private void bUserCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUserCadastraActionPerformed
        // TODO add your handling code here:
        String name, sobre,sId,sRegistro;
        name = cxUserNome.getText();
        sobre = cxUserSobrenome.getText();
        sId = cxUserId.getText();
        sRegistro = cxUserRegistro.getText();
        try{
            int nId = Integer.parseInt(sId);
            try{
                int nReg = Integer.parseInt(sRegistro);
                var cont = new DAOUsuario();
                var aux = new Usuario(nId,name,sobre,nReg);
                cont.incluir(aux);
                tUserConfirma.setText("Cadastro confirmado");
            }catch(NumberFormatException e){        
                cxMatricula.setText("Valor invalido");      
            }  
        }catch(NumberFormatException e){        
            cxUserId.setText("Valor invalido"); 
        }
        

    }//GEN-LAST:event_bUserCadastraActionPerformed

    private void bAutorCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAutorCadastraActionPerformed
        // TODO add your handling code here:
        String name, sobre,sId,biografia;
        name = cxAutorNome.getText();
        sobre = cxAutorSobrenome.getText();
        sId = cxAutorId.getText();
        biografia = cxBiografia.getText();
       
        try{
            int nId = Integer.parseInt(sId);
            var cont = new DAOAutores();
            var aux = new Autor(nId,name,sobre,biografia);
                cont.incluir(aux);
                tAutorConfirma.setText("Cadastro confirmado");
                lLivrosAutores.addItem(aux.getNome());
            }  
        catch(NumberFormatException e){        
            cxAutorId.setText("Valor invalido"); 
        }
        

    }//GEN-LAST:event_bAutorCadastraActionPerformed

    private void bCategoriaCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCategoriaCadastraActionPerformed
        // TODO add your handling code here:
        String sId,titulo;
        titulo = cxCategoriaTitulo.getText();
        sId = cxCategoriaId.getText();
       
        try{
            int nId = Integer.parseInt(sId);
            var cont = new DAOCategoria();
            var aux = new Categoria(nId,titulo);
                cont.incluir(aux);
                tCategoriaConfirma.setText("Cadastro confirmado");
                lLivrosCategoria.addItem(aux.getTitulo());
            }  
        catch(NumberFormatException e){        
            cxCategoriaId.setText("Valor invalido"); 
        }
        
    }//GEN-LAST:event_bCategoriaCadastraActionPerformed

    private void bLivroAddAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLivroAddAutoresActionPerformed
        // TODO add your handling code here:
        // Valor subtraido 1 por causa do valor default
        int index  = lLivrosAutores.getSelectedIndex() - 1;
        var cont = new DAOAutores();
        var aux =cont.localizar(index);
        AutoresProv.add(aux);
        String nomes = "";
        for(Autor autor : AutoresProv){
            nomes += autor.getNome() + ", ";
        }
        String total = "Autor(es) adicionado(s): " + nomes;
        tLivroAutoresAdd.setText(total);
    }//GEN-LAST:event_bLivroAddAutoresActionPerformed

    private void lLivrosAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lLivrosAutoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lLivrosAutoresActionPerformed

    private void bLivroAddCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLivroAddCategoriaActionPerformed
        // TODO add your handling code here:
        int index  = lLivrosCategoria.getSelectedIndex() - 1;
        var cont = new DAOCategoria();
        var aux =cont.localizar(index);
        CategoriaProv.add(aux);
        String nomes = "";
        for(Categoria categoria : CategoriaProv){
            nomes += categoria.getTitulo() + ", ";
        }
        String total = "Categorias(es) adicionada(s): " + nomes;
        tLivroCategoriaAdd.setText(total);
        
    }//GEN-LAST:event_bLivroAddCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAutorCadastra;
    private javax.swing.JButton bCadastra;
    private javax.swing.JButton bCategoriaCadastra;
    private javax.swing.JButton bLivroAddAutores;
    private javax.swing.JButton bLivroAddCategoria;
    private javax.swing.JButton bLivroCadastrar;
    private javax.swing.JButton bUserCadastra;
    private javax.swing.JTextField cxAutorId;
    private javax.swing.JTextField cxAutorNome;
    private javax.swing.JTextField cxAutorSobrenome;
    private javax.swing.JTextArea cxBiografia;
    private javax.swing.JTextField cxCategoriaId;
    private javax.swing.JTextField cxCategoriaTitulo;
    private javax.swing.JTextField cxId;
    private javax.swing.JTextField cxLivroId;
    private javax.swing.JTextField cxLivroNome;
    private javax.swing.JTextField cxMatricula;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxSobrenome;
    private javax.swing.JTextField cxUserId;
    private javax.swing.JTextField cxUserNome;
    private javax.swing.JTextField cxUserRegistro;
    private javax.swing.JTextField cxUserSobrenome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> lLivrosAutores;
    private javax.swing.JComboBox<String> lLivrosCategoria;
    private javax.swing.JTabbedPane pAdm;
    private javax.swing.JPanel pCadastraLivro;
    private javax.swing.JPanel pCadastraUser;
    private javax.swing.JPanel pCadastroFunc;
    private javax.swing.JTabbedPane pCadastroGeral;
    private javax.swing.JPanel pCategoria;
    private javax.swing.JLabel tAutorConfirma;
    private javax.swing.JLabel tCategoriaConfirma;
    private javax.swing.JLabel tConfirma;
    private javax.swing.JLabel tId;
    private javax.swing.JLabel tLivroAutoresAdd;
    private javax.swing.JLabel tLivroCategoriaAdd;
    private javax.swing.JLabel tLivroConfirma;
    private javax.swing.JLabel tMatricula;
    private javax.swing.JLabel tNome;
    private javax.swing.JLabel tSobrenome;
    private javax.swing.JLabel tUserConfirma;
    // End of variables declaration//GEN-END:variables
}
