/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import DAO.DAOAutores;
import DAO.DAOCategoria;
import DAO.DAOFuncionario;
import DAO.DAOLivro;
import DAO.DAOUsuario;
import Modelo.Usuario;
import Dados.Dados;
import Modelo.Autor;
import Modelo.Categoria;
import Modelo.Funcionario;
import Modelo.Livro;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author joaop
 */
public class TelaADM extends javax.swing.JFrame {
    private Livro livroAux;
    /**
     * Creates new form TelaADM
     */
    public TelaADM() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserCreates = new javax.swing.JFrame();
        dados = new javax.swing.JLabel();
        sobrenomeCampo = new javax.swing.JTextField();
        nomeCampo = new javax.swing.JTextField();
        RegCampo = new javax.swing.JTextField();
        IdCampo = new javax.swing.JTextField();
        CriarUser = new javax.swing.JToggleButton();
        mostraUser = new javax.swing.JTextField();
        FuncCreates = new javax.swing.JFrame();
        dados1 = new javax.swing.JLabel();
        sobrenomeCampo1 = new javax.swing.JTextField();
        nomeCampo1 = new javax.swing.JTextField();
        RegCampo1 = new javax.swing.JTextField();
        IdCampo1 = new javax.swing.JTextField();
        CriarFunc = new javax.swing.JToggleButton();
        criacao = new javax.swing.JTextField();
        LivroCreates = new javax.swing.JFrame();
        titulo = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        tituloTXTBox = new javax.swing.JTextField();
        listaAutores = new javax.swing.JComboBox<>();
        autoresTxt = new javax.swing.JLabel();
        botaoAddAutor = new javax.swing.JButton();
        testei = new javax.swing.JLabel();
        AutorCreates = new javax.swing.JFrame();
        titulp = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        tSobrenome = new javax.swing.JTextField();
        tBio = new javax.swing.JTextField();
        bCadastro = new javax.swing.JButton();
        tId = new javax.swing.JTextField();
        testeAutor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        OpcoesCadastroLista = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        UserCreates.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dados.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        dados.setText("Dados do User");

        sobrenomeCampo.setText("Sobrenome");
        sobrenomeCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobrenomeCampoActionPerformed(evt);
            }
        });

        nomeCampo.setText("Nome");
        nomeCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCampoActionPerformed(evt);
            }
        });

        RegCampo.setText("Registro Acadêmico");
        RegCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegCampoActionPerformed(evt);
            }
        });

        IdCampo.setText("Id");
        IdCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdCampoActionPerformed(evt);
            }
        });

        CriarUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CriarUser.setText("Criar");
        CriarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarUserActionPerformed(evt);
            }
        });

        mostraUser.setText("Criando um funcionario");
        mostraUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostraUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserCreatesLayout = new javax.swing.GroupLayout(UserCreates.getContentPane());
        UserCreates.getContentPane().setLayout(UserCreatesLayout);
        UserCreatesLayout.setHorizontalGroup(
            UserCreatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserCreatesLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(UserCreatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dados)
                    .addComponent(sobrenomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CriarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostraUser, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        UserCreatesLayout.setVerticalGroup(
            UserCreatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserCreatesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(dados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sobrenomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IdCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CriarUser)
                .addGap(18, 18, 18)
                .addComponent(mostraUser, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        FuncCreates.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dados1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dados1.setText("Dados do Funcionário");

        sobrenomeCampo1.setText("Sobrenome");
        sobrenomeCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobrenomeCampo1ActionPerformed(evt);
            }
        });

        nomeCampo1.setText("Nome");
        nomeCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCampo1ActionPerformed(evt);
            }
        });

        RegCampo1.setText("Matricula");
        RegCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegCampo1ActionPerformed(evt);
            }
        });

        IdCampo1.setText("Id");
        IdCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdCampo1ActionPerformed(evt);
            }
        });

        CriarFunc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CriarFunc.setText("Criar");
        CriarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarFuncActionPerformed(evt);
            }
        });

        criacao.setText("Criando funcinoario...");
        criacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FuncCreatesLayout = new javax.swing.GroupLayout(FuncCreates.getContentPane());
        FuncCreates.getContentPane().setLayout(FuncCreatesLayout);
        FuncCreatesLayout.setHorizontalGroup(
            FuncCreatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FuncCreatesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FuncCreatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dados1)
                    .addComponent(sobrenomeCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CriarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criacao, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FuncCreatesLayout.setVerticalGroup(
            FuncCreatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FuncCreatesLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(dados1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sobrenomeCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IdCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CriarFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(criacao, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titulo.setText("Informações dos Livros");

        idText.setText("ID");
        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });

        tituloTXTBox.setText("Título");
        tituloTXTBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloTXTBoxActionPerformed(evt);
            }
        });

        listaAutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Autores" }));
        listaAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAutoresActionPerformed(evt);
            }
        });

        autoresTxt.setText("Nenhum autor foi selecionado");

        botaoAddAutor.setText("+");
        botaoAddAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddAutorActionPerformed(evt);
            }
        });

        testei.setText("....");

        javax.swing.GroupLayout LivroCreatesLayout = new javax.swing.GroupLayout(LivroCreates.getContentPane());
        LivroCreates.getContentPane().setLayout(LivroCreatesLayout);
        LivroCreatesLayout.setHorizontalGroup(
            LivroCreatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LivroCreatesLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(LivroCreatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(testei, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloTXTBox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LivroCreatesLayout.createSequentialGroup()
                        .addGroup(LivroCreatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(autoresTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(listaAutores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAddAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81))
        );
        LivroCreatesLayout.setVerticalGroup(
            LivroCreatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LivroCreatesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addComponent(idText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloTXTBox, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LivroCreatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAddAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoresTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testei)
                .addGap(79, 79, 79))
        );

        titulp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titulp.setText("Criando um autor...");

        tNome.setText("Nome");
        tNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNomeActionPerformed(evt);
            }
        });

        tSobrenome.setText("Sobrenome");
        tSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSobrenomeActionPerformed(evt);
            }
        });

        tBio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tBio.setText("Biografia");

        bCadastro.setText("Cadastrar");
        bCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastroActionPerformed(evt);
            }
        });

        tId.setText("ID");
        tId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AutorCreatesLayout = new javax.swing.GroupLayout(AutorCreates.getContentPane());
        AutorCreates.getContentPane().setLayout(AutorCreatesLayout);
        AutorCreatesLayout.setHorizontalGroup(
            AutorCreatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutorCreatesLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(AutorCreatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tBio)
                    .addComponent(titulp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tNome)
                    .addComponent(tSobrenome)
                    .addComponent(bCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tId)
                    .addComponent(testeAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        AutorCreatesLayout.setVerticalGroup(
            AutorCreatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AutorCreatesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titulp)
                .addGap(18, 18, 18)
                .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tBio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bCadastro)
                .addGap(18, 18, 18)
                .addComponent(testeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Modo administrador");

        OpcoesCadastroLista.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        OpcoesCadastroLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionario", "Usuario", "Livro", "Autores", "Categorias de livro" }));
        OpcoesCadastroLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcoesCadastroListaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selecione o que  cadastrar");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(OpcoesCadastroLista, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OpcoesCadastroLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpcoesCadastroListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcoesCadastroListaActionPerformed
        // TODO add your handling code here:
        String cadastro = (String) OpcoesCadastroLista.getSelectedItem();
        //Funcionario Usuario Emprestimo Livro Autores Categorias de livro
        if( cadastro.equals("Usuario" )){
            
            UserCreates.setVisible(true);
            UserCreates.pack();
        }
        if(cadastro.equals("Funcionario")){
            FuncCreates.setVisible((true));
            FuncCreates.pack();
        }
        if(cadastro.equals("Livro")){
            LivroCreates.setVisible(true);
            LivroCreates.pack();
            
        }
        if(cadastro.equals("Autores")){
            AutorCreates.setVisible(true);
            AutorCreates.pack();
        }
            
    }//GEN-LAST:event_OpcoesCadastroListaActionPerformed

    private void sobrenomeCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobrenomeCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobrenomeCampoActionPerformed

    private void nomeCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCampoActionPerformed

    private void RegCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegCampoActionPerformed

    private void IdCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdCampoActionPerformed

    private void CriarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarUserActionPerformed
        // TODO add your handling code here:
        //Criação de um novo usuario
        String nId = IdCampo.getText();
        String nReg = RegCampo.getText();
        String name = nomeCampo.getText();
        String nick = sobrenomeCampo.getText();
        int id = Integer.valueOf(nId);
        int reg = Integer.valueOf(nReg);
        
        Usuario user = new Usuario(id,name,nick,reg);
        DAOUsuario controller = new DAOUsuario();
        controller.incluir(user);
        String conf = user.toString();
        mostraUser.setVisible(true);
        mostraUser.setText(conf);
    }//GEN-LAST:event_CriarUserActionPerformed

    private void sobrenomeCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobrenomeCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobrenomeCampo1ActionPerformed

    private void nomeCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCampo1ActionPerformed

    private void RegCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegCampo1ActionPerformed

    private void IdCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdCampo1ActionPerformed

    private void CriarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarFuncActionPerformed
        // TODO add your handling code here:
        //criacao de um novo funcionario 
        String nId = IdCampo1.getText();
        String nReg = RegCampo1.getText();
        String nome = nomeCampo1.getText();
        String sobreNome= sobrenomeCampo1.getText();
        int id = Integer.valueOf(nId);
        int reg = Integer.valueOf(nReg);
        Funcionario func = new Funcionario(id,nomeCampo1.getText(),sobrenomeCampo1.getText(),reg);
        DAOFuncionario controller = new DAOFuncionario();
        controller.incluir(func);
        criacao.setVisible((true));
        String cf = func.toString();
        criacao.setText(cf);
        
    }//GEN-LAST:event_CriarFuncActionPerformed

    private void criacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_criacaoActionPerformed

    private void mostraUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostraUserActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mostraUserActionPerformed

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextActionPerformed

    private void tituloTXTBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloTXTBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloTXTBoxActionPerformed

    private void tNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNomeActionPerformed

    private void tSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSobrenomeActionPerformed

    private void bCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastroActionPerformed
        // TODO add your handling code here:
        
        String nome = tNome.getText();
        String sobrenome = tSobrenome.getText();
        String bio = tBio.getText();
        String id = tId.getText();
        int nId = Integer.valueOf(id) ;
        Autor func = new Autor(nId,nome,sobrenome,bio);
        DAOAutores controller = new DAOAutores();
        controller.incluir(func);
        String total="";
        List<Autor> lista = controller.getLista();
        for(int i = 0;i<lista.size();i++){
            total = total + lista.get(i).toString();
        }
        testeAutor.setText(total);
        listaAutores.addItem(nome + " "+ sobrenome);
        
        
        
        
        
    }//GEN-LAST:event_bCadastroActionPerformed

    private void tIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdActionPerformed

    private void listaAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAutoresActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_listaAutoresActionPerformed

    private void botaoAddAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddAutorActionPerformed
        // TODO add your handling code here:
        //quando apertar o botao,o objeto vai ser adicionado
        int posicao = listaAutores.getSelectedIndex()-1;
        DAOAutores aController = new DAOAutores();        
        Autor aux = aController.localizar(posicao);
        livroAux = new Livro(0,"");
        livroAux.AdicionaAutor(aux);
        autoresTxt.setText("Adicionado: "+aux.getNome());
    }//GEN-LAST:event_botaoAddAutorActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame AutorCreates;
    private javax.swing.JToggleButton CriarFunc;
    private javax.swing.JToggleButton CriarUser;
    private javax.swing.JFrame FuncCreates;
    private javax.swing.JTextField IdCampo;
    private javax.swing.JTextField IdCampo1;
    private javax.swing.JFrame LivroCreates;
    private javax.swing.JComboBox<String> OpcoesCadastroLista;
    private javax.swing.JTextField RegCampo;
    private javax.swing.JTextField RegCampo1;
    private javax.swing.JFrame UserCreates;
    private javax.swing.JLabel autoresTxt;
    private javax.swing.JButton bCadastro;
    private javax.swing.JButton botaoAddAutor;
    private javax.swing.JTextField criacao;
    private javax.swing.JLabel dados;
    private javax.swing.JLabel dados1;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> listaAutores;
    private javax.swing.JTextField mostraUser;
    private javax.swing.JTextField nomeCampo;
    private javax.swing.JTextField nomeCampo1;
    private javax.swing.JTextField sobrenomeCampo;
    private javax.swing.JTextField sobrenomeCampo1;
    private javax.swing.JTextField tBio;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tSobrenome;
    private javax.swing.JLabel testeAutor;
    private javax.swing.JLabel testei;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField tituloTXTBox;
    private javax.swing.JLabel titulp;
    // End of variables declaration//GEN-END:variables
}
